[theme]

# Primary accent for interactive elements
primaryColor = '#dadfe4'

# Background color for the main content area
backgroundColor = '#e8e9ec' #00172B

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#ebedef'

# Color used for almost all text
textColor = '#0d0c0b'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"