[theme]

# Primary accent for interactive elements
primaryColor = '#E694FF'

# Background color for the main content area
backgroundColor = '#003153' #00172B

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#284F66'

# Color used for almost all text
textColor = '#f2f3f4'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"